language: minimal

dist: bionic

cache:
  npm: false
  directories:
    - "./node_modules"
    - "~/.pnpm-store"

env:
  global:
    - TARGET_VERSION=33
    - ANDROID_BUILD_TOOLS_VERSION=33.0.2
    - ANDROID_HOME=$HOME/android-sdk

before_install:
  # Update system packages and install required tools
  - sudo apt-get update
  - sudo apt-get install -y wget unzip

  # Install RVM (Ruby Version Manager)
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:rael-gc/rvm
  - sudo apt-get update
  - sudo apt-get install -y rvm
  - echo 'source /etc/profile.d/rvm.sh' >> ~/.bashrc
  - source /etc/profile.d/rvm.sh

  # Install the latest SDK tools
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip" -O commandlinetools.zip
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
  - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

  # Accept licenses and install packages
  - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
  - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-${TARGET_VERSION}" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "extras;google;m2repository" "extras;android;m2repository"

  # Install Java
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17-open
  - sdk use java 17-open
  - touch $HOME/.android/repositories.cfg

  # Fastlane dependencies
  - chmod +x ./sidekick/gradlew
  - rvm install 2.6.0
  - rvm use 2.6.0
  - gem install bundler -v 2.4.22
  - bundle install

  # Capacitor.js dependencies
  - nvm install 18
  - nvm use 18
  - npm install -g pnpm@8
  - pnpm config set store-dir ~/.pnpm-store
  - source /home/travis/.bashrc

install:
  - pnpm install
  - pnpm build
  - pnpm sync
  - cd ./sidekick
  - ./gradlew --version
  - ./gradlew clean assembleDebug

before_deploy:
  - openssl aes-256-cbc -K $encrypted_41783dd8bae9_key -iv $encrypted_41783dd8bae9_iv -in signing.tar.enc -out signing.tar -d
  - tar xvf signing.tar
  - fastlane alpha

deploy:
  provider: releases
  api_key:
    secure: U21XKaO+J4JoPiOgdNLyxTFCnM635lMO4rRlt3rPT/AJ5AA8Uev+g2mu3nyXhl3AEOe8KkJrdAFCgJG66cV0UT+fyNkhm/K/ABpeMcV0ZBPBh/L/liM2Icky/cCbYsrll444CBZBEe4dr0qXP/MYpB3NduaXn8x3pgqg2WP6EimO/ei/nzwBU9vaIjJOdk5vmCwKF5duNVtDrG5P1DqF2ic/rT5NCK15LjnSW2kGNynK1DuS1lWK6IsuPtUbtUPVBbgPmclU9C48SjTp1pDyNSWkONxT/SOmwHgiSzfWfaWUAvQEDLyhzQAVRXb/Y65dJCeXjMwYJeoTgF+r9ptqXR+a9BxEhAcXloKtfNyxOFFtqII0VaJWrfqdYGu8XJxjsxOvvnIBppzm556A42TEeWaXVJAidCPm7BAk+zjEh+9LhTv9pgzmpYde7cH8JKiTOzNksZ1YJhZFQe68KNh8rVcPYjn7LGtNHtQMMhZG+oxXpUWQRUr/pg4UHHH50clWzYeR7Oe5XYlyl0TFuaz9h8m5GJgrlLdSw8hKRK6Kx13Vq7U0pUMc+Q4EXVGxv7gkezm/dDxXWe9fAn4KcOTxP8verT9dXHdPOZgKsyGBYNThpawjV/tWQ53Zvepzq2IgA70mN672MKhfrmAocwK1uMXCfWC9+GIDOEMJVZbI8Gw=
  file_glob: true
  file: "sidekick/app/build/outputs/bundle/release/*.aab"
  skip_cleanup: true
  on:
    repo: TheCacophonyProject/sidekick
    tags: true
