# fastlane/Fastfile

default_platform(:android)

platform :android do
  desc "Build and upload the app to Google Play Alpha track"
  lane :alpha do
    # Load keystore properties from ~/.android/
    keystore_properties = {}
    keystore_path = File.expand_path("~/.android/keystore.properties")
    UI.user_error!("Couldn't find keystore.properties file at #{keystore_path}") unless File.exist?(keystore_path)
    File.open(keystore_path) do |file|
      file.each_line do |line|
        key, value = line.strip.split('=')
        keystore_properties[key] = value
      end
    end

    # Configure signing
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => keystore_properties["storeFile"],
        "android.injected.signing.store.password" => keystore_properties["storePassword"],
        "android.injected.signing.key.alias" => keystore_properties["keyAlias"],
        "android.injected.signing.key.password" => keystore_properties["keyPassword"]
      }
    )

    # Upload to Google Play
    upload_to_play_store(
      track: 'alpha',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      json_key: ENV['GOOGLE_PLAY_JSON_KEY']
    )
  end
end
