# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and upload the app to Google Play Alpha track"
  lane :alpha do
    # Load keystore properties
    keystore_properties = {}
    File.open("keystore.properties") do |file|
      file.each_line do |line|
        key, value = line.strip.split('=')
        keystore_properties[key] = value
      end
    end

    # Configure signing
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => keystore_properties["storeFile"],
        "android.injected.signing.store.password" => keystore_properties["storePassword"],
        "android.injected.signing.key.alias" => keystore_properties["keyAlias"],
        "android.injected.signing.key.password" => keystore_properties["keyPassword"]
      }
    )

    # Upload to Google Play
    upload_to_play_store(
      track: 'alpha',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      json_key: "api.json"
    )
  end
end
